repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black --line-length=120
        language: system
        pass_filenames: true
        files: '.+\.py$'
      - id: isort
        name: isort
        entry: poetry run isort --atomic --profile black --le 120
        language: system
        files: '.+\.py$'
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        files: '.+\.py$'
      - id: pyright
        name: pyright
        entry: poetry run pyright
        language: system
        files: '.+\.py$'
  - repo: https://github.com/python-poetry/poetry
    rev: 1.2.1
    hooks:
      - id: poetry-check
