[tool.poetry]
name = "administratorbot"
version = "0.1.0"
description = ""
authors = ["Alexandre Rulleau <rulleaualexandre@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
mypy = "^1.3.0"
black = "^23.3.0"
isort = "^5.12.0"
discord = "^2.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
